StydeNet/laravel-spanish-docs

docs/authorization.md
Affected file: authorization.md
=> improve readability in the phrase

docs/migrations.md
Cambiar la palabra **reversar** por **revertir**  para la documentación Laravel 6
=> Update migrations for Laravel 6

docs/api-authentication.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-ad74ad258c43cae7b1c4f0155e77324b
=> [6.0] Update api-authentication.md until "Alpha sort import statements"

docs/artisan.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-7af53ca4def61eb29ea73de8ff108cb4
=> [6.0] Update artisan.md until "Alpha sort import statements"

docs/authentication.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-6b57b661b9236f856cd4f0afa1bed671
=> [6.0] Update authentication.md until "Alpha sort import statements"

docs/authorization.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-92a5fbfd7cc9ebcc4989b65253f5bc01
=> [6.0] Update authorization.md until "Alpha sort import statements"

docs/broadcasting.md
Update until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-30ea189a41fdc579e0a00f165dcb98d0
=> Update broadcasting.md until "Alpha sort import statements"

docs/collections.md
Updated until:
https://github.com/laravel/docs/commit/2c6f18c6c4879127a70f92b79f07abaeaad40037#diff-40a34f27fa0507015ef983746697693e
=> Update collections.md until "Fixes grammar for Lazy Collection note"

docs/container.md
Updated until:
https://github.com/laravel/docs/commit/cfa4653f891f81a8dec59648f9d16c9651770bcf#diff-e855b9d7118d2f69fb6c0745ab0bcb32
=> Update container.md until "docs: Moved UploadController one step up"

docs/contracts.md
Updated until:
https://github.com/laravel/docs/commit/d78b4c9aa6461fd9ce27f50b54921e5c7bf1a676#diff-64a8597ea1c509a39649d370498f2fb8
=> Update contracts.md until "Revert 'update links'"

docs/controllers.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-568eb592fd969d4a574c5d9eabbcb4c8
=> Update controllers.md until "Alpha sort import statements"

docs/database.md
Updated until:
https://github.com/laravel/docs/commit/44e387a0bf3c8e96e1de71aab57fec11b73082eb#diff-1e080c892326e5bba749587eba8bcf9e
=> Update database.md until "Update database.md (Oct 1, 2019)"

docs/database-testing.md
Updated until:
https://github.com/laravel/docs/commit/1b5d0e0e44128f0cb6210b4f481a603874dd852a#diff-1620181c4412a72179f78bc2be6c6e68
=> Update database-testing.md until "Alpha sort import statements"

docs/dusk.md
Updated until:
https://github.com/laravel/docs/commit/1f3aa988caa048ed3c28974883fd6ce376efeff6#diff-e6022c244b5ac87a188f96034522efda
=> Update dusk.md until "create a database for Github Action"

docs/middleware.md
Update: https://github.com/StydeNet/laravel-spanish-docs/issues/306
- Fix some lists
=> Fix / Update middleware.md in Laravel 6.0

docs/helpers.md
Fix - https://github.com/StydeNet/laravel-spanish-docs/issues/304
=> Fix / Update helpers.md in Laravel 6.0

docs/eloquent-resources.md
Fix - https://github.com/StydeNet/laravel-spanish-docs/issues/301
=> Fix / Update eloquent-resources.md in Laravel 6.0

docs/eloquent-relationships.md
=> [Fix] - Fixing missing commits on eloquent-relationships

docs/pagination.md
=> updated doc according to commit 091747ff71fc948eea8749b5521957ce56173fea

docs/redis.md
=> Updated docs targeting Laravel 6.0 official doc

docs/frontend.md
Refactoring frontend documentation to version Laravel 6.x
=> [6.x] Refactor Frontend Documentation

docs/passport.md
=> [Fix] - Fixing missing commits on passport.md file

docs/passwords.md
=> [Fix] - Fixing missing commits on passwords.md file

docs/providers.md
=> [Fix] - Fixing missing commits on providers.md file

docs/queries.md
=> [Fix] - Fixing missing commits on queries.md file

docs/requests.md
=> [Fix] - Fixing missing commits on requests.md file

docs/frontend.md
Add documentation of section **Adding Presets**
=> [6.x] Adding Presets Documentation

docs/frontend.md
Referencia
https://github.com/laravel/docs/pull/5551
=> Add ui bootstrap command

docs/upgrade.md
I think this fixes and closes #353
=> Update spanish doc to latest english doc - upgrade.md

docs/views.md
=> Updating views.md

docs/valet.md
=> Updating valet.md

docs/testing.md
Updating testing file,
Issue #352
=> Updating testing.md

docs/eloquent-collections.md
Related to https://github.com/laravel/docs/pull/5501
=> Add available method list

docs/scheduling.md
Be more explicit about the time of execution for schedule tasks.
=>  Update scheduling.md
